# Generated by Django 5.0.4 on 2024-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
