# Generated by Django 5.0.4 on 2024-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='create_date',
        ),
    ]
