# Generated by Django 5.0.4 on 2024-06-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_department_description'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=2000)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('date_join_company', models.DateTimeField()),
                ('academic_level', models.CharField(max_length=200, null=True)),
                ('work_experience', models.CharField(max_length=2000, null=True)),
                ('marital_status', models.BooleanField()),
                ('identification_card', models.CharField(max_length=20)),
                ('card_photo', models.ImageField(upload_to='nhan_vien')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='position.position')),
            ],
        ),
    ]
